services:
  qa-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: qa-backend
    restart: unless-stopped
    networks:
      - qa-network

  qa-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: qa-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - qa-backend
    networks:
      - qa-network

networks:
  qa-network:
    driver: bridge